resources:
  pipelines:
  - pipeline: buildPipeline
    source: 'Test-Release'
    project: BlobFuse
    trigger: 
      branches:
        include:
          - main

stages: 
  - stage: TestArtifacts
    jobs:
      - job: TestArtifacts
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none
            persistCredentials: true
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'specific'
              project: 'BlobFuse'
              pipeline: 'Blobfuse2 Artifact'
              runVersionToDownload: 'latest'
              artifactName: 'blobfuse2-linux-unsigned'
          - script: |
              ls -la
              cd $(Pipeline.Workspace)/blobfuse2-linux-unsigned
              ls -la
            displayName: 'List files in the downloaded artifact'