variables:
  tags: 'fuse3'
  depends: 'fuse3'
  organization: 'azstorage'
  project: 'BlobFuse'
  pipelineId: 95
  run_id: 0
  patToken: $(System.AccessToken)
  status: 'inProgress'

parameters:
  - name: tag
    displayName: 'New Release Tag'
    type: string
    default: 'blobfuse2-'

  - name: unit_test
    displayName: 'Execute Unit Tests'
    type: boolean
    default: false

  - name: post_release
    displayName: 'Post Release on Github'
    type: boolean
    default: false

  - name: publish_artifacts
    displayName: 'Publish Artifacts to Linux Repos'
    type: boolean
    default: false

  - name: draft
    displayName: 'Post as Draft Release'
    type: boolean
    default: false

  - name: prerelease
    displayName: 'Post as PreRelease'
    type: boolean
    default: false

  - name: update_version
    displayName: 'Update Version'
    type: boolean
    default: false

# Do not trigger this pipeline automatically
trigger: none
pr: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    # The SDL Source analysis stage can only run in a windows environment due to limitations of Guardian tools. 
    # If you use Linux pool, we require an additional windows image in your pool to run the source analysis.
    sdl:   
      sourceAnalysisPool:
        name: blobfuse2-pool  # Name of your hosted pool
        image: windows2022-1espt
        os: windows  # OS of the image. Allowed values: windows, linux, macOS

    stages:
    - stage: BuildArtifacts
      jobs:
      - job: Set_1
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-pool
          image: ubuntu22-1espt
          os: linux
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(Build.ArtifactStagingDirectory)/blobfuse2-temp
            artifactName: 'blobfuse2-linux-unsigned'
            displayName: 'Publish Artifacts'

        # Job strategy is not supported in the 1ES pipeline template. Refer https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/faqs#:~:text=Unfortunately%2C%20it%20is%20not%20possible%20to%20use%20job%20strategy%20to%20specify%20pool%20at%20the%20pipeline.

        variables:
          - group: NightlyBlobFuse
          - name: root_dir
            value: '$(System.DefaultWorkingDirectory)'
          - name: work_dir
            value: '$(System.DefaultWorkingDirectory)/azure-storage-fuse'
          - name: unsigned
            value: '$(Build.ArtifactStagingDirectory)/blobfuse2-temp'
        
        steps:
        - checkout: none
        - script: |
            git clone https://github.com/Azure/azure-storage-fuse
          displayName: 'Checkout Code'
          workingDirectory: $(root_dir)
          
        # list commits from past 12hrs
        - script: |
            git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
            git --no-pager log --since="12 hours ago" --stat
          displayName: 'List Commits'
          workingDirectory: $(work_dir)
          
        # install dependencies required for compiling blobfuse
        - script: |
            touch ./newfile
            mv ./newfile $(unsigned)
          displayName: "Shifting file to Artifacts"
        
        - script: |
            echo "$(Build.BuildId)" 
          displayName: "Display Run ID"

      # - job: TriggerTestArtifactsPipeline
      #   timeoutInMinutes: 120
      #   pool:
      #     name: blobfuse2-pool
      #     image: ubuntu22-1espt
      #     os: linux
      #   steps:
      #     - checkout: none
      #     - bash: |
      #         az pipelines run --project 'BlobFuse' --id 95 --branch 'main' --organization 'https://dev.azure.com/azstorage/' --parameters "ReleasePipelineRunID=$(Build.BuildId)" --wait
      #       displayName: 'Trigger Pipeline Test-Artifacts'
      #       env:
      #         AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      #     - script: |
      #         echo "Pipeline continues"
      #       displayName: "Status"

      - job: TriggerAndWaitForTestPipeline
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-pool
          image: ubuntu22-1espt
          os: linux
        steps:
        - checkout : none
        - bash: |
            triggeredPipeline  = $(az pipelines run --project 'BlobFuse' --id 95 --branch 'main' --organization 'https://dev.azure.com/azstorage/' --parameters "ReleasePipelineRunID=$(Build.BuildId)")
            # Extract the run ID from the triggered pipeline
            run_id=$(echo $triggered_run | jq -r '.id')
            # Print the run ID
            echo "Triggered pipeline run ID: $run_id"
          displayName: 'Trigger Pipeline Test-Artifacts'
          env:
            AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      - job: CheckPipelineStatus
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-pool
          image: ubuntu22-1espt
          os: linux
        dependsOn: TriggerAndWaitForTestPipeline
        condition: succeeded()
        steps:
        - checkout : none
        - script: |
            echo "Checking the status of the triggered pipeline..."
            while true; do
              status=$(az pipelines runs show --organization https://dev.azure.com/$(organization) --project $(project) --pipeline-id $(pipelineId) --run-id $(run_id) --query status --output tsv --only-show-errors)
              echo "Current status: $status"
              if [[ "$status" == "completed" || "$status" == "canceled" || "$status" == "failed" ]]; then
                echo "Pipeline run $run_id has $status."
                break
              fi
              echo "Pipeline run $runId is still in progress. Checking again in 30 seconds..."
              sleep 30
            done
          displayName: 'Check Pipeline Status'
          env:
            AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      - job: ContinueOriginalPipeline
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-pool
          image: ubuntu22-1espt
          os: linux
        dependsOn: CheckPipelineStatus
        condition: succeeded()
        steps:
        - checkout : none
        - script: 
            if( "$status" == "completed" ); then
              echo "Pipeline run $run_id completed successfully. Continuing the original pipeline."
            else
              echo "Pipeline run $run_id failed or was canceled. Stopping the original pipeline."
              exit 1
            fi
          displayName: 'Continue Pipeline'

        # - script: |
        #     PIPELINE_ID=95  
        #     ORG_NAME="azstorage"
        #     PROJECT_NAME="BlobFuse"
        #     PAT=$(System.AccessToken)

        #     az pipelines list --output table --organization 'https://dev.azure.com/azstorage/' --project 'BlobFuse' 


        #     echo "Triggering Pipeline B"
        #     echo "https://dev.azure.com/$ORG_NAME/$PROJECT_NAME/_apis/pipelines/$PIPELINE_ID/runs?pipelineVersion=$(Build.BuildId)&api-version=7.1&waitForCompletion=true"  
            
        #     curl -X POST -u ":$PAT" \
        #     -H "Content-Type: application/json" \
        #     --data '{ "definitionId": '"$PIPELINE_ID"' }' \
        #     "https://dev.azure.com/$ORG_NAME/$PROJECT_NAME/_apis/pipelines/$PIPELINE_ID/runs?pipelineVersion=$(Build.BuildId)&api-version=7.1&waitForCompletion=true"
        #   displayName: "Trigger and Wait for Pipeline B"
        
        # - task: InvokeRESTAPI@1
          # displayName: 'Trigger Another Pipeline'
          # inputs:
          #   connectionType: 'connectedServiceName'
          #   serviceConnection: 'anuserviceconn'
          #   method: 'POST'
          #   urlSuffix: '/_apis/pipelines/95/runs?api-version=6.0-preview.1'
          #   headers: |
          #     {
          #       "Content-Type": "application/json"
          #     }
          #   body: |
          #     {
          #       "resources": {
          #         "repositories": {
          #           "self": {
          #             "refName": "refs/heads/main"
          #           }
          #         }
          #       }
          #     }
          #   waitForCompletion: true

        - script: |
            echo "Pipeline continues"
          displayName: "Status"
